### DISCUSSION TITLE
message store is not writeable, so putMessage is forbidden

### DISCUSSION THREAD

**Discussion by MmringZee** [apache/rocketmq#7950] [Q&A]
我在使用官方quickstart提供的demo访问部署在k8s上的单节点mq时,程序报错:
`2024-03-22T02:43:27.134+08:00 ERROR 1 --- [nio-9999-exec-2] c.p.r.controller.ProduceController : Failed to send message org.apache.rocketmq.client.java.exception.InternalErrorException: [request-id=406e0549-b4df-4aa7-b0ce-fc13878c83c1, response-code=50001] org.apache.rocketmq.proxy.common.ProxyException: service not available now. It may be caused by one of the following reasons: the broker's disk is full [CL: 0.91 CQ: 0.91 INDEX: 0.91], messages are put to the slave, message store has been shut down, etc.`

到broker.log查看,显示:
`
message store is not writeable, so putMessage is forbidden
`

这是yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rmq-proxy
  namespace: pscp-rocketmq
data:
  rmq-proxy.json: |
    {
      "rocketMQClusterName": "EkmsCluster",
      "grpcServerPort": 8081,      
      "remotingListenPort": 8080  
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-config
  namespace: pscp-rocketmq
data:
  broker-a.properties: |
    brokerClusterName = EkmsCluster
    brokerName = broker-a
    brokerId = 0
    deleteWhen = 04
    fileReservedTime = 48
    brokerRole = ASYNC_MASTER
    flushDiskType = ASYNC_FLUSH
    storePathRootDir=/data/rocketmq/store
    brokerRole=MASTER
    autoCreateSubscriptionGroup=true
    aclEnable=false
    brokerIP1 = broker-a.pscp-rocketmq.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker-a
  name: broker-a
  namespace: pscp-rocketmq
spec:
  type: ClusterIP
  ports:
  - port: 10911
    targetPort: 10911
    name: broker-port
  - port: 8081
    targetPort: 8081
    name: broker-proxy
  - port: 8080
    targetPort: 8080
    name: proxy-port
  selector:
    app: broker-a
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker-a
  namespace: pscp-rocketmq
spec:
  serviceName: broker-a
  replicas: 1
  selector:
    matchLabels:
      app: broker-a
  template:
    metadata:
      labels:
        app: broker-a
    spec:
      tolerations:
        - key: dgw.xxx.com.cn
          operator: Equal
          value: 'true'
          effect: NoSchedule            
      imagePullSecrets:
        - name: pscp-rocketmq-registrydev            
      containers:
      - name: broker-a
        image: registrydev.xxx.com.cn/pscp/rocketmq-5.1.4:v1
        command: ["sh","-c","/usr/local/rocketmq-5.1.4/bin/mqbroker -c /usr/local/rocketmq-5.1.4/conf/broker-a.properties --enable-proxy -n mqnamesrv.pscp-rocketmq.svc.cluster.local:9876"]
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPT
          value: "-server -XX:ParallelGCThreads=1 -Xms1g -Xmx1g -Xmn512m"
        resources:
          requests:
            memory: 128Mi
        volumeMounts:
          - mountPath: /root/logs
            name: pscp-rocketmq-cifs
            subPath: rocketmq-brokera-logs
          - mountPath: /data/rocketmq
            name: pscp-rocketmq-cifs
            subPath: rocketmq-brokera-store
          - name: broker-config
            mountPath: /usr/local/rocketmq-5.1.4/conf/broker-a.properties
            subPath: broker-a.properties
          - name: rmq-proxy
            mountPath: /usr/local/rocketmq-5.1.4/conf/rmq-proxy.json
            subPath: rmq-proxy.json            
      volumes:
      - name: broker-config
        configMap:
          name: rocketmq-config
      - name: rmq-proxy
        configMap:
          name: rmq-proxy
  volumeClaimTemplates:
  - metadata:
      name: pscp-rocketmq-cifs
      annotations:
        volume.beta.kubernetes.io/storage-class: "pscp-cifs-1"
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi

```
