### ISSUE TITLE
Broker error: java.lang.ClassCastException: java.lang.Class cannot be cast to org.apache.rocketmq.acl.AccessValidator

### ISSUE THREAD

**Issue by fengcharly** [apache/rocketmq#6630]
When I configured the following ACL file in the broker, the broker reported conversion failure:
user_ acl.yml: 
```
accounts:
 - accessKey: rocketmq2
   secretKey:  12345678
   admin: true
- accessKey: test
   secretKey: 12345678
   admin: true
```
Error reported:
java.lang.ClassCastException: java.lang.Class cannot be cast to org.apache.rocketmq.acl.AccessValidator
at org.apache.rocketmq.broker.BrokerController.initialAcl(BrokerController.java:915)
at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:781)
at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:224)
at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58)
