### ISSUE TITLE
Expected the service ProducerImpl-0 [FAILED] to be RUNNING, but the service has FAILED.

### ISSUE THREAD

**Issue by jzcccc** [apache/rocketmq#7508]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

mac,docker

### RocketMQ version

5.1.4

### JDK Version

1.8.0_372

### Describe the Bug

docker 部署时，proxy grpc端口是多少？是否需要自己定义？没有在文档看到

### Steps to Reproduce

无

### What Did You Expect to See?

能通过grpc发送消息

### What Did You See Instead?

Expected the service ProducerImpl-0 [FAILED] to be RUNNING, but the service has FAILED

**Comment by dingshuangxi888** [comment]
You can refer to the following configuration to obtain the gRPC port：
org.apache.rocketmq.proxy.config.ProxyConfig#grpcServerPort

**Comment by QinJiapeng** [comment]
我也遇到此问题，目前已经解决了
分享我的配置
mkdir -p -m 777 /mydata/rocketmq/conf
mkdir -p -m 777 /mydata/rocketmq/store
vim /mydata/rocketmq/conf/broker.conf
```sh
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
# 当前 broker 监听的 IP
brokerIP1 = 192.168.18.195
```
docker-compose.yml
```yml
version: '3'

services:
  rmqnamesrv:
    image: apache/rocketmq:5.1.4
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - /mydata/rocketmq/conf/broker.conf:/home/rocketmq/rocketmq-5.1.4/conf/broker.conf
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: ["sh","mqnamesrv"]

  broker:
    image: apache/rocketmq:5.1.4
    container_name: rmqbroker
    ports:
      - 8081:8081
      - 10909:10909
      - 10911:10911
    volumes:
      - /mydata/rocketmq/store:/home/rocketmq/store
      - /mydata/rocketmq/conf/broker.conf:/home/rocketmq/rocketmq-5.1.4/conf/broker.conf
    links:
      - rmqnamesrv:namesrv
    depends_on:
      - 'rmqnamesrv'
    environment:
      NAMESRV_ADDR: namesrv:9876
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: ["sh","mqbroker","-c","../conf/broker.conf","autoCreateTopicEnable=true","--enable-proxy"]

  rmqdashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    ports:
      - 8082:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876"
    links:
      - rmqnamesrv:namesrv
    depends_on:
      - 'rmqnamesrv'
```
